### ISSUE TITLE
Testsuite failing on Debian jessie

### ISSUE THREAD

**Issue by michaelweiser** [duritong/trocla#20]
Hi,

I'm in the process of packaging trocla for Debian. For that I needed to hack the testsuite to make it work. The patch can be found here: http://anonscm.debian.org/cgit/pkg-ruby-extras/trocla.git/tree/debian/patches/0001-testsuite.patch.

Issues are:
- without require 'yaml' ruby errors that constant YAML isn't known
- without the any_instance.expects -> should_receive change the testsuite doesn't run at all. rspec version on Debian jessie is 2.14
- the test for VERSION doesn't call read_config which obviously makes it fail. I copied over a password generation from another test to work around that.

As can be seen from the patch I don't have any clue how to program rspec. Any hints on how to fix this properly would be greatly appreciated.

Thanks
Michael

**Comment by duritong** [comment]
Hi Michael,

thanks a lot for the suggestions.

* Require yaml

We can do that.

*  any_instance.expects

I think this should read

    expect_any_instance_of(Trocla).to receive(:read_config).and_return(test_config)

* VERSION

I don't think this is necessary. If we don't do the call then we shouldn't expect it. We can put these into 2 different contexts.

I can do the changes if you don't want the fame for the commit.

**Comment by michaelweiser** [comment]
Hi!

I'm a sucker for fame and promptly gave it a whirl in https://github.com/duritong/trocla/pull/22. At least in my Debian package it does seem to work fine.

Thanks!
Michael

**Comment by michaelweiser** [comment]
Mhmm, while it's working on my Debian box it's failing in Travis now. I'm stumped. I guess it's to do with the rspec version on Debian vs. Travis.

**Comment by duritong** [comment]
I merged and should have it fixed for jessie and ruby 1.8 (though that is another dep).

**Comment by duritong** [comment]
Let me know if anything (beside a proper release - that will follow soon) to fix/support you're packaging work.
