### ISSUE TITLE
TTL/expires for drivers that support them

### ISSUE THREAD

**Issue by Poil** [duritong/trocla#28]
Hi,

A feature request, perhaps I'll do it in the next future, but perhaps you already think it.

It'll be nice to add an expires option when you use cassandra or other backend that support it (http://www.rubydoc.info/gems/moneta/Moneta/Expires)

We'll be able to auto-regenerated passwords all 30 days for some key.

Best regards,

**Comment by Poil** [comment]
Edit : it's possible for all driver https://github.com/minad/moneta#expiration via Moneta::Expires

**Comment by duritong** [comment]
I think this would be quite a nice idea, wouldn't mind merging such a patch.

**Comment by duritong** [comment]
Should be implemented with 3777b63
