### ISSUE TITLE
yaml and password beggining with a comma

### ISSUE THREAD

**Issue by Poil** [duritong/trocla#30]
Hi,

On ruby 2.0.0pXXX when password are beginning with a comma it crash trocla.

Ref. https://github.com/minad/moneta/issues/83

I have to edit the yaml file to quote them

best regards

**Comment by duritong** [comment]
Ok thabks for reporting. I guess will wait till moneta fixed the issue.

**Comment by duritong** [comment]
Seems to be actually a psych problem https://github.com/tenderlove/psych/issues/240

**Comment by Poil** [comment]
Hi,
Yep, and it seems that if we use ruby 1.9 or 2.0 (and never 1.8) the strings are "good quoted".
So I think we can close this issue.
Best regards,
