### ISSUE TITLE
puppetserver jdbc

### ISSUE THREAD

**Issue by timogoebel** [duritong/trocla#41]
When using trocla with puppetserver, I randomly get these errors:

```
Java::ComMysqlJdbcExceptionsJdbc4::CommunicationsException: Communications link failure\n\nThe last packet successfully received from the server was 518,437 milliseconds ago.  The last packet sent successfully to the server was 11 milliseconds ago.
```

The connection to the database looks fine.
The config looks like this:

```
store_options:
  adapter: :Sequel
  adapter_options:
    :db: jdbc:mysql://127.0.0.1:13306/trocladb
    :password: loldbpassword
    :table: trocla
    :user: trocla
```

What's the best way to debug this issue?
Is there some retry mechanism missing?

**Comment by timogoebel** [comment]
This dosen't seem to be an issue with trocla itself. I created a PR for https://github.com/minad/moneta/pull/112 that has more details on my proposed way to fix this.

**Comment by duritong** [comment]
Thank you for the update. yes, should be fixed within moneta and as far as I can see, trocla does already everything right... :-)

**Comment by timogoebel** [comment]
> as far as I can see, trocla does already everything right... :-)

Yes, it does. Thanks for the this awesome gem, @duritong!
