### ISSUE TITLE
Puppetserver: jruby no such file to load -- bcrypt

### ISSUE THREAD

**Issue by johnjoepo** [duritong/trocla#47]
I have a problem using trocla on our PuppetServer.

PuppetServer uses `jruby 1.7.26 (1.9.3p551) 2016-08-26 69763b8 on OpenJDK 64-Bit Server VM 1.8.0_131-b12 +jit [linux-amd64]`

I installed trocla on our PuppetServer and have some problems executing trocla using bcrypt.
After executing `trocla create user1 bcrypt` the following error is thrown:

```
NameError: undefined local variable or method 'bcrypt' for main:Object
        (root) at test.rb:1
        invoke at jruby_core.clj:259
        invoke at jruby_core.clj:253
  invokeStatic at ruby.clj:9
        invoke at ruby.clj:6
  invokeStatic at subcommand.clj:37
        invoke at subcommand.clj:26
  invokeStatic at ruby.clj:13
      doInvoke at ruby.clj:11
  invokeStatic at core.clj:646
  invokeStatic at main.clj:314
        invoke at main.clj:310
  invokeStatic at main.clj:421
      doInvoke at main.clj:384
```

I also checked that bcrypt is installed:
```
puppetserver gem list

*** LOCAL GEMS ***

apipie-bindings (0.2.0)
bcrypt (3.1.11 java)
...
sequel (4.43.0)
text (1.3.1)
trocla (0.2.3)
```

Can you please help me?

Thank you.

**Comment by duritong** [comment]
@johnjoepo do you mind commenting what fixed your problem?

**Comment by johnjoepo** [comment]
@duritong 
The initial Problem was that the wrong version of the bcrypt gem was installed (non-java version)
After installing the correct version, the Problem mentioned above occurred.

The Problem was fixed by restarting the puppetserver.

It was my fault, trocla just works fine - Silly me :)

**Comment by duritong** [comment]
Cool, thanks for clarification. I mainly asked, because this might happen to others and then it's usually a pain finding a bug report exactly matching your problem, but silently closed.
