### ISSUE TITLE
feature request: dummy store

### ISSUE THREAD

**Issue by scoopex** [duritong/trocla#51]
Trocla should provide a dummy store which accepts but ignores store operations and returns dummy values for any get operation for test automation.

This is useful if you:
- use manually created values in trocla which fail in a test environment because they are fetch by (i.e. offical ssl certificates) 
- have to test a high number of hosts (performance)
- you do not want to to configure and preload a test storage for testing purposes

It seems that you just have to implement a new store in lib/trocla/stores/.

Do you have any hints?

**Comment by duritong** [comment]
So trocla supports loading stores, that are external to trocla. See [Storage backends](https://github.com/duritong/trocla#storage-backends). What you need to do:

1. Write a class that inherits from Trocla::Store and implements all the required methods, as well as the behavior you want. Basically:
```
class MyStore < Trocla::Storage
  #your stuff
end`
2. Store that class e.g. in /etc/trocla/mystore.rb
3. Your storage configuration then should look like:
```
store: MyStore
store_require: /etc/trocla/mystore.rb
```

done.

**Comment by scoopex** [comment]
I wrote a very simple store for my testing purposes: https://github.com/scoopex/trocla/blob/dummy-store/lib/trocla/stores/dummy.rb

**Comment by scoopex** [comment]
Thanks, i wrote a trivial dummy store for my purposes. I will test this in my environment.

https://github.com/scoopex/trocla/blob/dummy-store/lib/trocla/stores/dummy.rb

**Comment by duritong** [comment]
let me know if something doesn't work or if you have improvements regarding the documentation, I would welcome PRs! :-) Otherwise I would close this, as it's all done.
