### ISSUE TITLE
test suite fails on "selfsigned is able to create self signed cert without being a ca by default"

### ISSUE THREAD

**Issue by anarcat** [duritong/trocla#63]
we've been getting this in Debian for a while now:

Failures:

```
  1) Trocla::Format::X509 x509 selfsigned is able to create self signed cert without being a ca by default
     Failure/Error: expect(verify(cert,cert)).to be false

       expected false
            got true
     # ./spec/trocla/formats/x509_spec.rb:47:in `block (3 levels) in <top (required)>'

Finished in 3 minutes 0 seconds (files took 3.63 seconds to load)
168 examples, 1 failure
```

Failed examples:

```
rspec ./spec/trocla/formats/x509_spec.rb:34 # Trocla::Format::X509 x509 selfsigned is able to create self signed cert without being a ca by default

/usr/bin/ruby2.7 -I/usr/share/rubygems-integration/all/gems/rspec-support-3.9.3/lib:/usr/share/rubygems-integration/all/gems/rspec-core-3.9.2/lib /usr/share/rubygems-integration/all/gems/rspec-core-3.9.2/exe/rspec --pattern ./spec/\*\*/\*_spec.rb failed
ERROR: Test "ruby2.7" failed. Exiting.
dh_auto_install: error: dh_ruby --install /build/1st/trocla-0.2.3/debian/trocla returned exit code 1
make[1]: *** [debian/rules:21: override_dh_auto_install] Error 25
```

This was filed in Debian as https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=982154

This led to the removal of trocla from Debian testing, which means it's unlikely that it will be shipped with the next stable release (bullseye).

This might be related to the new Ruby release in bullseye (2.7 vs 2.5 in buster).

**Comment by duritong** [comment]
The reason for that has been summarized here: https://github.com/openssl/openssl/issues/15146

**Comment by anarcat** [comment]
thanks, i included your patch in Debian, and this will hopefully make it to experimental (and then, hopefully, to unstable). it's unlikely to make it to bullseye, but at least we have a path forward now.
