### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by geor-g** [duritong/trocla#72]
Hi,

As the Debian freeze, to get the next stable version in shape, is coming closer: any chance of cutting a new release, to include all the recent fixes?

Thanks!

**Comment by duritong** [comment]
can you give a deadline?

**Comment by geor-g** [comment]
end of the year would be nice.

**Comment by duritong** [comment]
The main work is getting a working ci back, meaning going somewhere else than travis, e.g. github actions.

Any help is appreciated

**Comment by geor-g** [comment]
I started to work on this via #73. Works in my fork, not sure why it doesn't yet in this MR.

**Comment by duritong** [comment]
Let's merge and make it work...

Thank you so far - I guess once merged, we need to do minor cleanups...

**Comment by duritong** [comment]
looks good to me: https://github.com/duritong/trocla/actions/runs/3405208404

Thank you so far!

**Comment by duritong** [comment]
Happy new year: https://rubygems.org/gems/trocla/versions/0.5.0
