### ISSUE TITLE
expire option is presented inconsistently on readme

### ISSUE THREAD

**Issue by Clebam** [duritong/trocla#79]
Hi,

the option is shown as `expires` with an `s` on the readme but is used as expire without an s inside the code.

It seems to work fine with vault 'store' without an `s`.

**Comment by duritong** [comment]
The code uses `expires` all over, so it's definitely correct in the README.

Are you getting an error when using it with an `s`?

**Comment by Clebam** [comment]
Hi @duritong , I faced the problem with this part of the code : https://github.com/duritong/trocla/blob/main/lib/trocla/stores/vault.rb#L74

```
# Works
$trocla_options = {
        'expire' => $trocla_key_expires,
      }

# Did not work
$trocla_options = {
        'expires' => $trocla_key_expires,
      }
```

**Comment by duritong** [comment]
ok, that is an issue with the vault backend then.

**Comment by fe80** [comment]
Hello @duritong 

Seems totally legit, that's a bug :+1:
